FROM pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime
WORKDIR /app
COPY requirements-species.txt ./requirements-species.txt
RUN conda install python=3.7
RUN pip install --upgrade pip && pip install -r requirements-species.txt
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
COPY SpeciesClassification/FasterRCNNDetection/model/utils/nms/ /app/FasterRCNNDetection/model/utils/nms/
RUN cd /app/FasterRCNNDetection/model/utils/nms/ && python3 build.py build_ext --inplace
#COPY SpeciesClassification/inceptionv4-8e4777a0.pth /root/.cache/torch/checkpoints/inceptionv4-8e4777a0.pth
#COPY SpeciesClassification/se_resnext101_32x4d-3b2fe3d8.pth /root/.cache/torch/checkpoints/se_resnext101_32x4d-3b2fe3d8.pth
COPY SpeciesClassification/inceptionv4-8e4777a0.pth /root/.torch/models/inceptionv4-8e4777a0.pth
COPY SpeciesClassification/se_resnext101_32x4d-3b2fe3d8.pth /root/.torch/models/se_resnext101_32x4d-3b2fe3d8.pth
COPY SpeciesClassification/species_classification.2019.12.00.pytorch /root/.torch/models/species_classification.2019.12.00.pytorch
ENTRYPOINT ["bash", "classify_images.sh"]
